apiVersion: v1
kind: Pod
metadata:
  name: test-pod-01
spec:
  containers:
    - image: nvcr.io/nvidia/pytorch:19.10-py3
      name: nvidia-test
      imagePullPolicy: IfNotPresent
      command: ['sh','-c','python /main.py']
      volumeMounts:
        - mountPath: /main.py
          name: program
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
  volumes:
    - hostPath:
        path: /home/amax/package/main.py
      name: program