apiVersion: v1
kind: Pod
metadata:
  name: test-pod-02
spec:
  containers:
    - image: nvcr.io/nvidia/pytorch:19.10-py3
      name: nvidia-test
      imagePullPolicy: IfNotPresent
      command: ['sh','-c','sh /entrypoint.sh']
      volumeMounts:
        - mountPath: /main.py
          name: program
        - mountPath: /entrypoint.sh
          name: entrypoint
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
  volumes:
    - hostPath:
        path: /home/amax/package/main.py
      name: program
    - hostPath:
        path: /home/amax/package/dual-process.sh
      name: entrypoint
